apiVersion: v1
kind: DynamicContextSource
metadata:
  name: dynamic-mcp-context
spec:
  resources:
    - uri: "simple-mcp://system/overview"
      description: "An overview of the system under management, loaded from a file."
      contentFile: "system_overview.txt"

    - uri: "simple-mcp://system/uptime"
      description: "Current system uptime, load average, and user count."
      command: "uptime"
      intervalSeconds: 30

    - uri: "simple-mcp://system/health"
      description: "Basic system health status. Reads CPU, GPU, and other temperatures from /sys."
      # This command first checks if any thermal_zone devices exist before trying to read them.
      command: |
        if [ -z "$(ls /sys/class/thermal/thermal_zone* 2>/dev/null)" ]; then 
          echo "No thermal sensors detected (VM environment)."; 
        else 
          for zone in /sys/class/thermal/thermal_zone*; do 
            echo -n "$(cat $zone/type): "; 
            awk '{printf "%.1f°C\n", $1/1000}' $zone/temp; 
          done; 
        fi
      intervalSeconds: 30

    - uri: "simple-mcp://system/memory"
      description: "System memory usage in megabytes."
      command: "free -m"
      intervalSeconds: 60

    - uri: "simple-mcp://system/disk"
      description: "Disk usage for the root filesystem."
      command: "df -h /"
      intervalSeconds: 300
    
    - uri: "simple-mcp://system/network-interfaces"
      description: "Lists all network interfaces and their IP addresses."
      command: "ip addr show"
      intervalSeconds: 300

  contextItems:
    - name: NodeIPAddress
      description: "Retrieve the primary node IP address used for the default route."
      command: "ip -4 route get 1.1.1.1 | awk '{print $7}' | tr -d '\n'"

    - name: KernelVersion
      description: "Get the running kernel version."
      command: "uname -r"

    - name: GetServiceLogs
      description: "Retrieves the last 10 log lines for any specific systemd service."
      command: "journalctl -u {{.serviceName}} -n 10 --no-pager"
      parameters: ["serviceName"]

    - name: GetKernelLog
      description: "Retrieves the last 10 lines from the kernel message buffer (dmesg). Useful for hardware or driver issues."
      command: "dmesg -T | tail -n 10"

    - name: GetNetworkConnections
      description: "Lists all active TCP and UDP network connections and listening ports (similar to netstat)."
      command: "ss -tuna"

    - name: GetFirewallRules
      description: "Lists the current firewall (iptables) rules. Output is limited to the first 100 lines."
      command: "iptables -L -n -v | head -n 100"

    - name: GetServiceStatus
      description: "Check the status of any specific systemd service (e.g., active, inactive, failed)."
      command: "systemctl is-active {{.serviceName}} || true"
      parameters: ["serviceName"]

    - name: ListFailedServices
      description: "Lists all systemd services that have entered a 'failed' state."
      command: "systemctl --failed --no-pager"

    - name: PackageVersion
      description: "Gets the installed version of a specific RPM package."
      command: "rpm -q {{.package}}"
      parameters: ["package"]
