apiVersion: v1
kind: DynamicContextSource
metadata:
  name: dynamic-mcp-context
spec:
  resources:
    # --- Existing System Context ---
    - uri: "unified-core://system/overview"
      description: "An overview of the Unified Core (UC) v0.5 system, its architecture, and administration."
      content: |
        You are managing a Unified Core (UC) system, which is an image-based, immutable operating system similar to Flatcar or Talos. The UC system
        is built from SLE Micro components, but when referring to the operating system, use the Unified Core name.

    - uri: "simple-mcp://scratch-space"
      content: |
        Simple-mcp offers a persistent scratch space that can be used for creating files and directories needed for execution of some of its MCP tools.
        CreateFile, ReadFile, ModifyFile, DeleteFile, CreateDirectory, RemoveDirectory and List directory all operate in this scratch space, and are not
        allowed to use paths that would escape out of it. No absolute paths (starting with "/") or paths containing ".." are allowed. All simple-mcp's 
        tools execute with this space as their current working directory.

    # --- Elemental 3 Configuration & Documentation ---
    - uri: "elemental://guide"
      description: "Guide for building custom OS images using Elemental 3."
      content: |
        # Elemental 3 Build Guide
        
        To build a custom Linux image using Elemental, follow this workflow:
        
        1. **Get Examples**: Read all the `elemental://config/` resources to get valid YAML content for required files. All the files are required for a successful build.
        2. **Validate**: Check `elemental://schema` to ensure your
           changes (if any) match the required structure. The schema covers only
           files directly in the config directory. Files in the 'network' subdirectory  follow the
           standard nmstate format and files in the 'kubernetes' subdirectory are
           standard Kubernetes and Helm configuration files.
        3. **Create Config**:
           - Use `CreateDirectory` to create a working folder (e.g., `config`).
           - Use `CreateFile` to write the example content (adapted as needed) to files inside that folder.
        4. **Build**:
           - Call `Elemental3Build` pointing to your config directory.
           - Specify the output file (e.g., `my-image.raw`).
           - Only ImageType `raw` is supported.

    - uri: "elemental://schema"
      description: "JSON Schema definition for the Elemental 3 configuration directory."
      contentFile: "elemental-schema.json"

    - uri: "elemental://config/butane.yaml"
      description: "Working example of butane.yaml"
      contentFile: "elemental-example/butane.yaml"

    - uri: "elemental://config/kubernetes.yaml"
      description: "Working example of kubernetes.yaml"
      contentFile: "elemental-example/kubernetes.yaml"

    - uri: "elemental://config/kubernetes/config/agent.yaml"
      description: "Working example of kubernetes/config/agent.yaml"
      contentFile: "elemental-example/kubernetes/config/agent.yaml"

    - uri: "elemental://config/kubernetes/config/server.yaml"
      description: "Working example of kubernetes/config/server.yaml"
      contentFile: "elemental-example/kubernetes/config/server.yaml"

    - uri: "elemental://config/kubernetes/helm/values/rancher.yaml"
      description: "Working example of kubernetes/helm/values/rancher.yaml"
      contentFile: "elemental-example/kubernetes/helm/values/rancher.yaml"

    - uri: "elemental://config/kubernetes/manifests/ip-pool.yaml"
      description: "Working example of kubernetes/manifests/ip-pool.yaml"
      contentFile: "elemental-example/kubernetes/manifests/ip-pool.yaml"

    - uri: "elemental://config/kubernetes/manifests/l2-adv.yaml"
      description: "Working example of kubernetes/manifests/l2-adv.yaml"
      contentFile: "elemental-example/kubernetes/manifests/l2-adv.yaml"

    - uri: "elemental://config/kubernetes/manifests/rke2-ingress-config.yaml"
      description: "Working example of kubernetes/manifests/rke2-ingress-config.yaml"
      contentFile: "elemental-example/kubernetes/manifests/rke2-ingress-config.yaml"

    - uri: "elemental://config/network/node1.qemu.yaml"
      description: "Working example of network/node1.qemu.yaml"
      contentFile: "elemental-example/network/node1.qemu.yaml"

    - uri: "elemental://config/network/node2.libvirt.yaml"
      description: "Working example of network/node2.libvirt.yaml"
      contentFile: "elemental-example/network/node2.libvirt.yaml"

    - uri: "elemental://config/suse-product-manifest.yaml"
      description: "Working example of suse-product-manifest.yaml"
      contentFile: "elemental-example/suse-product-manifest.yaml"

    - uri: "elemental://config/install.yaml"
      description: "Working example of install.yaml"
      contentFile: "elemental-example/install.yaml"

    - uri: "elemental://config/release.yaml"
      description: "Working example of release.yaml"
      contentFile: "elemental-example/release.yaml"

  tools:
    - name: Uptime
      description: "Current system uptime, load average, and user count."
      command: "uptime"

    - name: MemoryUsage
      description: "System memory usage."
      command: "free -h"

    - name: DiskUsage
      description: "Disk usage for the root filesystem."
      command: "df -h /"
    
    - name: NetworkInterfaces
      description: "Lists all network interfaces and their IP addresses."
      command: "ip addr show"

    - name: Temperatures
      description: "Reads hardware temperatures from /sys/class/hwmon."
      command: |
        if [ -z "$(ls /sys/class/hwmon/hwmon*/temp*_input 2>/dev/null)" ]; then
          echo "No thermal sensors detected."
        else
          for h in /sys/class/hwmon/hwmon*; do
            n=$(cat "$h/name" 2>/dev/null || echo "hwmon")
            for i in "$h"/temp*_input; do
              [ -f "$i" ] || continue
              b=$(basename "$i" _input)
              l="$b"
              if [ -f "$h/${b}_label" ]; then
                l=$(cat "$h/${b}_label")
              fi
              awk -v n="$n" -v l="$l" '{printf "%s %s: %.1f°C\n", n, l, $1/1000}' "$i"
            done
          done
        fi

    - name: HostOSImage
      description: "Retrieve the current installed and running image URL from /etc/elemental/deployment.yaml. The URL contains the current release version (0.5 or 0.6)"
      command: "grep uri: /etc/elemental/deployment.yaml | awk '{ print $2; }'"

    - name: RKE2Status
      description: "Check RKE2 service health. Reports the status string (e.g., active, inactive)."
      command: "systemctl is-active rke2-server.service || true"

    - name: NodeIPAddress
      description: "Retrieve the primary node IP address used for the default route."
      command: "ip -4 route get 1.1.1.1 | awk '{print $7}' | tr -d '\n'"

    - name: GetKubernetesPods
      description: "Lists the currently running Kubernetes pods and their statuses in a kubectl output format."
      command: "KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/data/*/bin/kubectl get pods -A"

    - name: GetCRIContainers
      description: "Lists the currently running CRI containers and their statuses in a crictl output format."
      command: "CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml /var/lib/rancher/rke2/bin/crictl ps"

    - name: KernelVersion
      description: "Get the running kernel version."
      command: "uname -r"

    - name: GetKubernetesNodes
      description: "Lists all Kubernetes nodes and their statuses (e.g., Ready, NotReady)."
      command: "KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/data/*/bin/kubectl get nodes -o wide"

    - name: GetKubernetesServices
      description: "Lists all Kubernetes services and their ClusterIPs/ports."
      command: "KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/data/*/bin/kubectl get services -A"

    - name: DescribeKubernetesPod
      description: "Get detailed information about a specific pod, including events. This is the primary tool for debugging a 'Pending' or 'CrashLoopBackOff' pod."
      command: "KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/data/*/bin/kubectl describe pod {{.podName}} -n {{.namespace}}"
      parameters: ["podName", "namespace"]

    - name: GetCRIImages
      description: "Lists all container images currently available on the node's disk."
      command: "CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml /var/lib/rancher/rke2/bin/crictl images"

    - name: GetServiceLogs
      description: "Retrieves the last 10 log lines for any specific systemd service."
      command: "journalctl -u {{.serviceName}} -n 10 --no-pager"
      parameters: ["serviceName"]

    - name: GetKernelLog
      description: "Retrieves the last 10 lines from the kernel message buffer (dmesg). Useful for hardware or driver issues."
      command: "dmesg -T | tail -n 10"

    - name: GetNetworkConnections
      description: "Lists all active TCP and UDP network connections and listening ports (similar to netstat)."
      command: "ss -tuna"

    - name: GetFirewallRules
      description: "Lists the current firewall (iptables) rules. Output is limited to the first 100 lines."
      command: "iptables -L -n -v | head -n 100"

    - name: GetServiceStatus
      description: "Check the status of any specific systemd service (e.g., active, inactive, failed)."
      command: "systemctl is-active {{.serviceName}} || true"
      parameters: ["serviceName"]

    - name: ListFailedServices
      description: "Lists all systemd services that have entered a 'failed' state."
      command: "systemctl --failed --no-pager"

    - name: Reboot
      description: "Reboots the system."
      command: "echo 'System rebooting.' && reboot"
      timeoutSeconds: 1

    - name: PackageVersion
      description: "Gets the installed version of a specific RPM package."
      command: "rpm -q {{.package}}"
      parameters: ["package"]

    - name: ListSystemImages
      description: "Lists available tags for a given repository in registry.suse.de. Example repository: devel/unifiedcore/releases/0.6/containers/uc-base-os-kernel-rt or devel/unifiedcore/releases/0.6/containers/uc-base-os-kernel-default"
      command: "curl -s https://registry.suse.de/v2/{{.repository}}/tags/list"
      parameters: ["repository"]

    - name: Elemental3CtlSystemUpgrade
      description: "Triggers a system upgrade to the specified OCI image. You should usually list available tags first."
      command: "elemental3ctl upgrade --os-image {{.osImage}} | grep -v 'deployment file not found' || echo 'System upgrade initiated.'"
      parameters: ["osImage"]
      timeoutSeconds: 600
      async: true

    - name: Elemental3Version
      description: "Checks the installed version of the Elemental 3 CLI."
      command: "elemental3 version"

    - name: Elemental3Build
      description: "Builds a custom OS image. Requires a valid config directory. Check the elemental://guide resource before using. This is a long-running process, so it's better to continue chatting with the user and check the progress on each interaction."
      # We include --local to support local container storage if needed, though remote OCI is default.
      # The command outputs to stdout/stderr, which the async handler captures.
      command: "elemental3 build --config-dir {{.configDir}} --output {{.outputFile}} --image-type {{.imageType}}"
      parameters: ["configDir", "outputFile", "imageType"]
      timeoutSeconds: 1800 # 30 minutes allow time for pulling images and building
      async: true

    - name: Elemental3BuildInstaller
      description: "Builds an installation media (ISO or RAW) from an OS image and config."
      command: "elemental3ctl build-iso  --os-image {{.osImage}} --output {{.outputDir}}"
      parameters: ["mediaType", "osImage", "outputDir"]
      timeoutSeconds: 1800
      async: true
