apiVersion: v1
kind: DynamicContextSource
metadata:
  name: dynamic-mcp-context
spec:
  resources:
    # --- Existing System Context ---
    - uri: "simple-mcp://system/overview"
      description: "An overview of the Unified Core (UC) v0.5 system, its architecture, and administration."
      content: |
        You are managing a Unified Core (UC) system, which is an image-based, immutable operating system similar to Flatcar or Talos. The UC system
        is built from SLE Micro components, but when referring to the operating system, use the Unified Core name.

    - uri: "simple-mcp://system/uptime"
      description: "Current system uptime, load average, and user count."
      command: "uptime"
      intervalSeconds: 30

    - uri: "simple-mcp://system/health"
      description: "Basic system health status. Reads CPU, GPU, and other temperatures from /sys."
      command: |
        if [ -z "$(ls /sys/class/thermal/thermal_zone* 2>/dev/null)" ]; then 
          echo "No thermal sensors detected (VM environment)."; 
        else 
          for zone in /sys/class/thermal/thermal_zone*; do 
            echo -n "$(cat $zone/type): "; 
            awk '{printf "%.1f°C\n", $1/1000}' $zone/temp; 
          done; 
        fi
      intervalSeconds: 30

    - uri: "simple-mcp://system/memory"
      description: "System memory usage in megabytes."
      command: "free -m"
      intervalSeconds: 60

    - uri: "simple-mcp://system/disk"
      description: "Disk usage for the root filesystem."
      command: "df -h /"
      intervalSeconds: 300
    
    - uri: "simple-mcp://system/network-interfaces"
      description: "Lists all network interfaces and their IP addresses."
      command: "ip addr show"
      intervalSeconds: 300

    # --- Elemental 3 Configuration & Documentation ---

    - uri: "simple-mcp://elemental/guide"
      description: "Guide for building custom OS images using Elemental 3."
      content: |
        # Elemental 3 Build Guide
        
        To build a custom Linux image using Elemental, follow this workflow:
        
        1. **Get Examples**: Read `simple-mcp://elemental/examples` to get valid YAML content for `install.yaml`, `release.yaml`, etc.
        2. **Validate**: Check `simple-mcp://elemental/schema` to ensure your configuration matches the required structure.
        3. **Create Config**:
           - Use `CreateDirectory` to create a working folder (e.g., `my-config`).
           - Use `CreateFile` to write the example content (adapted as needed) to files inside that folder.
        4. **Build**:
           - Call `Elemental3Build` pointing to your config directory.
           - Specify the output file (e.g., `my-image.raw`).
           - Only ImageType `raw` is supported.

    - uri: "simple-mcp://elemental/schema"
      description: "JSON Schema definition for the Elemental 3 configuration directory."
      contentFile: "elemental-schema.json"

    - uri: "simple-mcp://elemental/examples"
      description: "Working examples of Elemental 3 configuration files (install.yaml, release.yaml, kubernetes.yaml)."
      contentFile: "elemental-examples.json"

  contextItems:
    # --- Existing System Tools ---
    - name: HostOSImage
      description: "Retrieve the current installed and running image URL from /etc/elemental/deployment.yaml. The URL contains the current release version (0.5 or 0.6)"
      command: "grep uri: /etc/elemental/deployment.yaml | awk '{ print $2; }'"

    - name: RKE2Status
      description: "Check RKE2 service health. Reports the status string (e.g., active, inactive)."
      command: "systemctl is-active rke2-server.service || true"

    - name: NodeIPAddress
      description: "Retrieve the primary node IP address used for the default route."
      command: "ip -4 route get 1.1.1.1 | awk '{print $7}' | tr -d '\n'"

    - name: GetKubernetesPods
      description: "Lists the currently running Kubernetes pods and their statuses in a kubectl output format."
      command: "KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/data/*/bin/kubectl get pods -A"

    - name: GetCRIContainers
      description: "Lists the currently running CRI containers and their statuses in a crictl output format."
      command: "CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml /var/lib/rancher/rke2/bin/crictl ps"

    - name: KernelVersion
      description: "Get the running kernel version."
      command: "uname -r"

    - name: GetKubernetesNodes
      description: "Lists all Kubernetes nodes and their statuses (e.g., Ready, NotReady)."
      command: "KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/data/*/bin/kubectl get nodes -o wide"
    
    - name: GetKubernetesServices
      description: "Lists all Kubernetes services and their ClusterIPs/ports."
      command: "KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/data/*/bin/kubectl get services -A"

    - name: DescribeKubernetesPod
      description: "Get detailed information about a specific pod, including events. This is the primary tool for debugging a 'Pending' or 'CrashLoopBackOff' pod."
      command: "KUBECONFIG=/etc/rancher/rke2/rke2.yaml /var/lib/rancher/rke2/data/*/bin/kubectl describe pod {{.podName}} -n {{.namespace}}"
      parameters: ["podName", "namespace"]

    - name: GetCRIImages
      description: "Lists all container images currently available on the node's disk."
      command: "CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml /var/lib/rancher/rke2/bin/crictl images"

    - name: GetRKE2Logs
      description: "Retrieves the last 10 log lines from the RKE2 service (rke2-server)."
      command: "journalctl -u rke2-server -n 10 --no-pager"

    - name: GetServiceLogs
      description: "Retrieves the last 10 log lines for any specific systemd service."
      command: "journalctl -u {{.serviceName}} -n 10 --no-pager"
      parameters: ["serviceName"]

    - name: GetKernelLog
      description: "Retrieves the last 10 lines from the kernel message buffer (dmesg). Useful for hardware or driver issues."
      command: "dmesg -T | tail -n 10"

    - name: GetNetworkConnections
      description: "Lists all active TCP and UDP network connections and listening ports (similar to netstat)."
      command: "ss -tuna"

    - name: GetFirewallRules
      description: "Lists the current firewall (iptables) rules. Output is limited to the first 100 lines."
      command: "iptables -L -n -v | head -n 100"

    - name: GetServiceStatus
      description: "Check the status of any specific systemd service (e.g., active, inactive, failed)."
      command: "systemctl is-active {{.serviceName}} || true"
      parameters: ["serviceName"]

    - name: ListFailedServices
      description: "Lists all systemd services that have entered a 'failed' state."
      command: "systemctl --failed --no-pager"

    - name: Reboot
      description: "Reboots the system."
      command: "echo 'System rebooting.' && reboot"
      timeoutSeconds: 1

    - name: PackageVersion
      description: "Gets the installed version of a specific RPM package."
      command: "rpm -q {{.package}}"
      parameters: ["package"]

    # --- Elemental 3 System Management Tools ---

    - name: ListImageTags
      description: "Lists available tags for a given repository in registry.suse.de. Example repository: devel/unifiedcore/releases/0.6/containers/uc-base-os-kernel-rt"
      command: "curl -s https://registry.suse.de/v2/{{.repository}}/tags/list"
      parameters: ["repository"]

    - name: Elemental3CtlSystemUpgrade
      description: "Triggers a system upgrade to the specified OCI image. You should usually list available tags first."
      command: "elemental3ctl upgrade --os-image {{.osImage}} | grep -v 'deployment file not found' || echo 'System upgrade initiated.'"
      parameters: ["osImage"]
      timeoutSeconds: 600
      async: true

    # --- Elemental 3 Build Tools ---

    - name: Elemental3Version
      description: "Checks the installed version of the Elemental 3 CLI."
      command: "elemental3 version"

    - name: Elemental3Build
      description: "Builds a custom OS image. Requires a valid config directory (install.yaml, release.yaml). This is a long-running process."
      # We include --local to support local container storage if needed, though remote OCI is default.
      # The command outputs to stdout/stderr, which the async handler captures.
      command: "elemental3 build --config-dir {{.configDir}} --output {{.outputFile}} --image-type {{.imageType}}"
      parameters: ["configDir", "outputFile", "imageType"]
      timeoutSeconds: 1800 # 30 minutes allow time for pulling images and building
      async: true

    - name: Elemental3BuildInstaller
      description: "Builds an installation media (ISO or RAW) from an OS image and config. Useful for bootstrap."
      command: "elemental3ctl build-installer --type {{.mediaType}} --os-image {{.osImage}} --output {{.outputDir}}"
      parameters: ["mediaType", "osImage", "outputDir"]
      timeoutSeconds: 1800
      async: true
